---
- hosts: localhost
  vars:
    state: present
    s3_bucket: kams-devops
    key: terraform.tfstate
    region: us-west-2
    app_env: dev
  tasks:
    - name: Run Terraform scripts
      terraform:
        project_path: "./"
        state: "{{ vars.state }}"
        backend_config:
          s3_bucket: "{{ vars.s3_bucket }}"
          key: "{{ vars.key }}"
          region: "{{ vars.region }}"
        variable_file: "{{ vars.app_env }}.tfvars"
        workspace: "{{ vars.app_env }}"