---
- hosts: localhost
  become: True
  tasks:
    - name: Run Terraform scripts
      terraform:
        project_path: "./"
        state: present
        backend_config:
          s3_bucket: "kams-devops"
          key: "terraform.tfstate"
          region: "us-west-2"
        variable_file: "dev.tfvars"
        workspace: "dev"